### ISSUE TITLE
Volume and vserver are not following previous pages in tutorial

### ISSUE THREAD

**Issue by simonpie** [NetAppDocs/ontap-fli#17]
Page: [FLI online: Importing the data](https://docs.netapp.com/us-en/ontap-fli/san-migration/task_fli_online_importing_the_data.html)

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: [FLI online: Importing the data](https://docs.netapp.com/us-en/ontap-fli/san-migration/task_fli_online_importing_the_data.html)
