### ISSUE TITLE
documentation appears inaccurate

### ISSUE THREAD

**Issue by wolftales** [NetAppDocs/ontap-fli#25]
### Page URL

https://docs.netapp.com/us-en/ontap-fli/san-migration/task_multipath_verification_for_windows_hosts.html

### Page title

Multipath verification for Windows hosts

### Summary

I'm using the our LOD windows 2019 for Iscsi testing.  Disk mgmt does not have an MPIO tab under properties, and mpclaim --v is an invalid switch. 

These appear to need to be revalidated

 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Thanks you @wolftales for bringing this to our attention. We'll investigate and update the documentation accordingly.

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This has now been addressed in our documentation here: https://docs.netapp.com/us-en/ontap-fli/san-migration/task_multipath_verification_for_windows_hosts.html
