### ISSUE TITLE
Text missing from "Migration types supported by Foreign LUN Import" topic?

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap-fli#6]
Page: [Migration types supported by Foreign LUN Import](https://docs.netapp.com/us-en/ontap-fli/san-migration/concept_migration_types_supported_by_foreign_lun_import.html)

This topic seems to be missing content. Note the dangling sentence at the end.

**Comment by netapp-forry** [comment]
Thanks Adam.
@netapp-chandaj - Looks like a possible migration issue, please investigate.

**Comment by netapp-chandaj** [comment]
This issue has been resolved. 
https://docs.netapp.com/us-en/ontap-fli/san-migration/concept_migration_types_supported_by_foreign_lun_import.html
